version: "3.3"

services:
  db:
   image: postgres
   environment:
      POSTGRES_DB: "postgresdb"
      POSTGRES_HOST_AUTH_METHOD: "trust"


  api:
    ports:
      - 8081:8080
    build:
      dockerfile: docker/Dockerfile
      context: .
    depends_on:
      - db


