# Generated by Django 2.2.5 on 2020-03-31 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinguser',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingbooking.ParkingPlace'),
        ),
    ]
