# Generated by Django 2.2.5 on 2020-03-31 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingbooking', '0002_auto_20200331_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinguser',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkingbooking.ParkingPlace'),
        ),
        migrations.AddField(
            model_name='usercar',
            name='electric',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkingbooking.UserCar'),
        ),
    ]
