# Generated by Django 2.2.5 on 2020-04-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingbooking', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercar',
            name='electric',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
