# Generated by Django 2.2.5 on 2020-04-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingbooking', '0005_auto_20200401_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
