# Generated by Django 2.2.5 on 2020-04-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingbooking', '0006_auto_20200401_0830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='usercar',
            name='electric',
            field=models.BooleanField(default=False),
        ),
    ]
